### ISSUE TITLE
Normalizing individual channels with different inputRanges

### ISSUE THREAD

**Issue by JanaFischer** [BodenmillerGroup/cytomapper#24]
When using the normalize function the same inputRange values are applied to all channels of the image but occasionally a certain channel needs to be enahnced more than others. A work around is to adjust the contrast in the bcg parameter for specific channels.

**Comment by nilseling** [comment]
My suggestion would be to add the option for a list input: `inputRange = list(H3 = c(0, 130), CD8a = c(0, 50))` to specify the clipping range for individual channels. All channels that are not specified will not be altered

**Comment by nilseling** [comment]
This is now a feature. E.g. 
`cur_images <- normalize(pancreasImages, inputRange = list(H3 = c(0, 70), CD99 = c(0, 100)))`
