### ISSUE TITLE
extend vignette section 8.1 Subsetting the SingleCellExperiment object

### ISSUE THREAD

**Issue by toobiwankenobi** [BodenmillerGroup/cytomapper#25]
If the user wants to visualize the occurrence of a variable with a large number of unique elements, the image legend contains all possible elements (which appears very messy with more than ~15 elements) from the said variable. This is true even if an image contains only a fraction of all elements. The subsetting of the 'sce' object allows to display only the elements relevant for an image.

The following images show an example of how subsetting the `sce` object can help to improve the interpretability of images and the corresponding legend. Here, chemokine clusters are shown. Subsetting of the `sce` object retains only clusters relevant for the current image. 

The vignette could be extended to illustrate such cases and help the user understand why subsetting an `sce` object can be helpful and sometimes necessary. 

**Without subsetting**
![000003](https://user-images.githubusercontent.com/38858452/81575407-4aae9b80-93a7-11ea-9a0f-d7381f170d62.png)

**With subsetting**
![000052](https://user-images.githubusercontent.com/38858452/81575415-4c785f00-93a7-11ea-84a4-8e039e3c47bc.png)

**Comment by nilseling** [comment]
Done!
