### ISSUE TITLE
legend with many elements is not fully visible

### ISSUE THREAD

**Issue by toobiwankenobi** [BodenmillerGroup/cytomapper#26]
legend entries are cut off when there are too many unique elements (see image). there is maybe a way to illustrate all unique elements in multiple columns instead of just one.

![000002](https://user-images.githubusercontent.com/38858452/81577252-7fbbed80-93a9-11ea-8b4b-5f473896d787.png)

**Comment by nilseling** [comment]
I would recommend subsetting the `SingleCellExperiment` to the information (e.g. cell-type) that you want to visualize. This will also subset the legend and give you a clearer colouring.
Just to document the approach here ;)
