### ISSUE TITLE
How to export cell mask from qupath?

### ISSUE THREAD

**Issue by kaizen89** [BodenmillerGroup/cytomapper#48]
Hi,
I have a naive question, I have an image overlay with 13 markers on which I performed cell segmentation on Qupath, I was wandering if you know hot to export the mask as a tif file to use with cytomapper.
Thank you

**Comment by nilseling** [comment]
Hi @kaizen89 

unfortunately I'm not so familiar with the scripting environment of qupath. But I googled around and found the post here: https://forum.image.sc/t/mask-script-doesnt-work-in-qupath-m4/33259 the corrected script works for me to export the segmentation masks. But these are exported as binary images (background: 0, cell: 1) and therefore not suitable for cytomapper. But the script could be a start for what you want to do. You could also ask the developers of qupath for help. At the end you will just need a segmentation mask where each cell is defined as a set of pixels with the same integer ID. 
Best,

Nils

**Comment by kaizen89** [comment]
Thanks. While looking for a solution in qupath, what other tools would you recommend for multiplexed immunochemistry images?

**Comment by nilseling** [comment]
QuPath is probably the best option. There is also [CytoMAP](https://www.sciencedirect.com/science/article/pii/S221112472030423X) which offers more options for interactive multiplexed image analysis. Also check out [steinbock](https://github.com/BodenmillerGroup/steinbock) and the [ImcSegmentationPipeline](https://github.com/BodenmillerGroup/ImcSegmentationPipeline) for segmenting multiplexed images. As part of these pipelines, [CellProfiler](https://cellprofiler.org/) comes in quite handy. Nowadays, there are also some nice [napari](https://napari.org/) plugins available for this sort of analysis. This list is by far not complete, just tools that I had a look at in the past.

**Comment by nilseling** [comment]
I'll close this issue for now. Please reopen if I can support you with `cytomapper` related things :)

**Comment by kaizen89** [comment]
Thanks, I finally found a script to export the cell mask with qupath here https://www.imagescientist.com/scripting-export-images#masks

**Comment by nilseling** [comment]
This is really useful, thanks!
