### ISSUE TITLE
Warinings and errors when reading tif file exported with qupath

### ISSUE THREAD

**Issue by kaizen89** [BodenmillerGroup/cytomapper#50]
Hi,
I used qupath to export a tif file with 13 channels and antother file containing the cell mask.
When I read the multichannel file I get
```
images <- loadImages("/mnt/sda3/qupath_analysis/image_export_original.tif", pattern="tif")
Warning messages:
1: In readTIFF(x, all = all, ...) :
  TIFFReadDirectory: Unknown field with tag 50838 (0xc696) encountered
2: In readTIFF(x, all = all, ...) :
  TIFFReadDirectory: Unknown field with tag 50839 (0xc697) encountered
```
```
channelNames(images)
NULL
```
```
channelNames(images)= c("nuclei","ker","CD3", 'CD68', 'CD8', 'CXCL13', 'DC-LAMP','FAP', 'FOXP3', 'KI67','MZB1',
+                         'PD1','PDPN','TCF1')
Error in dimnames(y) <- `*vtmp*` : 
  length of 'dimnames' [3] not equal to array extent
```
I am using the dev version of Cytomapper.
Have you ever encountered this issue?

**Comment by nilseling** [comment]
Hmm, that doesn't look right. What's the result of `dim(images[[1]])`? It looks like the exported tiff might not be the right file type. Could you potentially share the tiff?

**Comment by kaizen89** [comment]
```
images[[1]]
Image 
  colorMode    : Color 
  storage.mode : double 
  dim          : 5106 5041 3 14 
  frames.total : 42 
  frames.render: 14 

imageData(object)[1:5,1:6,1,1]
     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    0    0    0    0    0    0
[2,]    0    0    0    0    0    0
[3,]    0    0    0    0    0    0
[4,]    0    0    0    0    0    0
[5,]    0    0    0    0    0    0
```
Link to access the image and mask
https://drive.google.com/drive/folders/1w_WGlmAZX8Zo-0iKnRsHAwWSdBlhtIRo?usp=sharing

**Comment by nilseling** [comment]
Hi @kaizen89 

so the mask is fine. The multi-channel images were not exported as grayscale images and were read in as multi-channel RGB. In ImageJ I have opened the multi-channel tif, converted it to RGB and then back to 8-bit. This changed the multi-channel RGB to grayscale. The grayscale image can be read in with `cytomapper` and you can proceed as planed :) 
Best,

Nils

**Comment by kaizen89** [comment]
Thanks!
