### ISSUE TITLE
Missing system libraries on Ubuntu 20.04 for EBImage

### ISSUE THREAD

**Issue by jwindhager** [BodenmillerGroup/cytomapper#52]
I know that this does not directly affect cytomapper, but probably good to document it somewhere.

On Ubuntu 20.04, the following system libraries are required for EBImage:

    sudo apt-get install libfftw3-3 libfftw3-dev libtiff5-dev

**Comment by jwindhager** [comment]
Furthermore, for building the development version of cytomapper with vignettes, I needed to install:

    sudo apt-get install libfontconfig1-dev

as well as the following R packages from CRAN:

    install.packages(c("rmarkdown", "cowplot"))

and the following Bioconductor package:

    BiocManager::install("BiocStyle")

**Comment by nilseling** [comment]
Hmm, for the R packages they should be installed by default since they are listed under [Suggests](https://github.com/BodenmillerGroup/cytomapper/blob/master/DESCRIPTION). How did you install the cytomapper devel?

**Comment by jwindhager** [comment]
Maybe those are ignored by `devtools::install_github`?

Did the following, as indicated in the README:

    devtools::install_github("BodenmillerGroup/cytomapper", build_vignettes = TRUE)

**Comment by nilseling** [comment]
Ok, I'll have a look. The `build_vignettes` parameter should trigger exactly this.

**Comment by nilseling** [comment]
Alright, thanks for checking this. I have now updated the installation instructions in the [README](https://github.com/BodenmillerGroup/cytomapper/blob/master/README.md) and started a [cytomapper wiki](https://github.com/BodenmillerGroup/cytomapper/wiki/Installation-issues) with more detailed installation instructions.
