### ISSUE TITLE
Reader function for single-channel tiffs

### ISSUE THREAD

**Issue by nilseling** [BodenmillerGroup/cytomapper#60]
As discussed with @ellispatrick it might be good to add a function that reads in single-channel tiffs into multi-channel CytoImageList objects. In general this is the format often used to store low-plex IF data or data prepared for histoCAT.

**Comment by nilseling** [comment]
Hi @ellispatrick, 

I have now added an option to read single-channel images into multi-channel `CytoImageList` objects in #72. Could you please test it by installing the devel version via:

```
library(remotes)
remotes::install_github("BodenmillerGroup/cytomapper", build_vignettes = TRUE, dependencies = TRUE)
``` 

You should be able to read in multiple sub-folders or files of a single folder via

```
CIL <- loadImages("path/to/folders", single_channel = TRUE)
```

Let me know how this goes.

**Comment by nick-robo** [comment]
Hey @nilseling,

I tested it out, and it seems to work as expected. Thanks for adding it!

**Comment by nilseling** [comment]
Great, thanks! Closing now
