### ISSUE TITLE
mcols to colData

### ISSUE THREAD

**Issue by ellispatrick** [BodenmillerGroup/cytomapper#62]
It would be fantastic if measureObjects expanded the information in mcols of the masks/images into the colData of the resulting SingleCellExperiment/SpatialExperiment.

**Comment by nilseling** [comment]
That's a good point, thanks! I'll add it soon.

**Comment by nilseling** [comment]
This is now added in `v1.9.1` via #63. Please reopen if you're experiencing problems.
