### ISSUE TITLE
Modifying `h5FilesPath` for `CytoImageList` object 

### ISSUE THREAD

**Issue by ynanli** [BodenmillerGroup/cytomapper#76]
Hi,

I wanted to know if modifying the directories of h5 files on the `CytoImageList` object is possible. I liked the feature that we could use `mcol()` to include metadata in the images. However, we cannot save the image objects as rds files without `on_disk` mode due to limited memory. Then the h5 files always need to be saved at a specific path, making collaboration a bit difficult. 

So, can I modify the `h5FilesPath` after constructing the object?

Here are some efforts without success:
`for (i in  seq_along(images2)) { 
  new_path <- paste0(New.h5FilesPath, "/", names(images2)[i], ".h5")
  path(seed(images2[[names(images2)[i]]])) <- new_path
}` 

`for (i in  seq_along(images2)) {
  DelayedArray::seed(images2[[names(images2)[i]]])@filepath <- paste0(New.h5FilesPath, "/", names(images2)[i], ".h5")
}` 

It always returns:
`Error in .Call2("C_h5getdimscales", filepath, name, scalename, PACKAGE = "HDF5Array") : 
  H5Fis_hdf5() returned an error`

I know this is not a cytomapper issue, but it would be good to know if we could modify the object.

Many thanks!

**Comment by nilseling** [comment]
Hi @ynanli 

you could move the whole folder where you saved the HDF5 files and read them in from the new location using `loadImages`. Depending on what you have done with the images (normalization or compensation), the image within the HDF5 file might not have the same name as the HDF5 file anymore. You can control which image from within the HDF5 file is read in using the `name` argument. For transfering the `mcols`, you could save them separately as RDS file and send it to your collaborators. They will just need to make sure that the order of the images still matches.

**Comment by ynanli** [comment]
Hi @nilseling 

Thanks! Nice way to work around it! Did not think of transferring `mcols` separately at all. 😅

**Comment by nilseling** [comment]
No problem :) let me know if there are issues with this approach
