### ISSUE TITLE
Cytomappershiny questions

### ISSUE THREAD

**Issue by ssaintsoon** [BodenmillerGroup/cytomapper#78]
Hi, I'm currently trying steinbock pipeline to process IMC datasets, and following ImagingWorkshop2023 sessions now. I didn't participate in the workshop, so I'm not sure if it's appropriate to leave a question here. Please tell me if it's inappropriate. Also, I have to mention that I have no experiences with R or other programming tools, so please understand that questions can be silly.

With downloaded raw data (Patient1-4.zip), I successfully ran all of codes (except spillover correction) until 'Manual labeling of cells'.
I noticed cytomappershiny is needed, so I ran the code.

library(cytomapper)
if (interactive()) {
    cytomapperShiny(object = spe, mask = masks, image = images, 
                    cell_id = "ObjectNumber", img_id = "sample_id")
}

The only code I change was "image = images_comp" to "image = images" because I didn't correct spillover.

With the code, cytomappershiny (v1.12.0) was appeared, so I manually gated cells.
(With 2 plots, Ecad-CD3+ --> CD8 and CD4, and Patient1_001.)
I checked CD8+ selection was appropriate for other images (Patient1_002, Patient2_001, ...)
and saved gated-cells as 'CD8.rds'.

But I noticed that 'gated-cells' subfolder has 4 numbers of CD8.rds (like CD8_1.rds, CD8_2.rds, ...)
  1) One of my question is, why there are 4 kinds of cell.rds? Is it because the number of patients is 4?
  If I can open the file, it might be confirmed but idk how to open it or visualize it.

  2) Second, my 'CD8.rds' was only few hundred KB but CD8_1.rds was a thousand KB.
      So I suspected it is ROI-merged .rds (I mean, gated cells in Patient_1_001 ~ 003 were concatenated into CD8_1 and so on) 
      If it's correct, does it mean I have to saved gated-cells for all of individual ROIs,
      like CD8_1_001.rds, CD8_1_002.rds, CD8_1_003.rds ?

  3) Hoch et al. (2022) showed masks also could be loaded on image,
      but I couldn't find out any options in my window. How can it be loaded?

Any comments or suggestions will be very helpful. Thanks for careful answers in community.

**Comment by nilseling** [comment]
Hi @ssaintsoon 

When you click on the ? in the app, a help page pops up. Have a look at this to see if your question gets answered. In brief, you gate per image. So if you want to gate CD8 T cells on 4 images you will need to download 4 files.

**Comment by nilseling** [comment]
Closing as I'm assuming that this is resolved now
