### ISSUE TITLE
compImage function

### ISSUE THREAD

**Issue by SchulzDan** [BodenmillerGroup/cytomapper#92]
It seems that something has changed with the compensation of images. When using on disk storage and overwriting the original counts with the compensated counts and saving the h5 files then the h5 files cannot be read any more using the the loadImages function. When overwrite = FALSE, then the h5 files can still be read using the loadImages function.

However, even the h5 files than cannot be read using loadImages seem intact and can be read using rhdf5 package.

Will give you some data for reproducibility in a bit.

**Comment by nilseling** [comment]
What's the `name` argument you are using in `loadImages` when reading in data from the h5 files?

**Comment by lassedochreden** [comment]
Hi @SchulzDan, I had a look and as suggested already by @nilseling, the `name` argument has to be specified in your setting. 

Specifically, after image compensation with `overwrite = TRUE` the dataset name entry of the **.h5 file** contains a new suffix `_comp`, which you now have to specify in `loadImages` via the `name` argument. 

Will close this for now.

**Comment by SchulzDan** [comment]
thanks, indeed the mistake was somewhere upstream in our code...
